# Generated by Django 4.2 on 2023-12-19 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['.mp4', '.mkv'])]),
        ),
    ]
