# Generated by Django 4.2 on 2023-12-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videos_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
