# Generated by Django 4.2 on 2023-12-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_videos_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
